schemas:
  "https://schemas.stacspec.org/v1.0.0/collection-spec/json-schema/collection.json": "local_schemas/v1.0.0/collection.json"
  "https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json": "local_schemas/v1.0.0/item.json"
  "https://schemas.stacspec.org/v1.0.0/catalog-spec/json-schema/catalog.json": "local_schemas/v1.0.0/catalog.json"